# This is a basic workflow to help you get started with Actions
# adjusted via https://docs.docker.com/ci-cd/github-actions/

name: ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        run: |
          # build tag based on the repository basename and the VERSION variable in the Dockerfile 
           TAG=$(printf "${PWD##*/}" | tr -d "\n" | sed s/bx_//g):$(grep "ENV VERSION " Dockerfile | head -n 1 | cut -f 3 -d " ")--$(git rev-parse HEAD | cut -c 1-7)
          # build the container and tag it
           docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/$TAG
          # login Dockerhub
           echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          # push the container to Dockerhub 
           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$TAG 
